create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  excerpt text,
  content text not null,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.anime_links (
  id bigint generated by default as identity primary key,
  anilist_id integer not null,
  provider text not null,
  url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  anilist_id integer not null,
  title text,
  cover_url text,
  created_at timestamptz not null default now(),
  unique(user_id, anilist_id)
);

alter table public.posts enable row level security;
alter table public.anime_links enable row level security;
alter table public.bookmarks enable row level security;

create policy "posts public read" on public.posts
for select using (true);

create policy "links public read" on public.anime_links
for select using (true);

create policy "users read own bookmarks" on public.bookmarks
for select using (auth.uid() = user_id);

create policy "users insert own bookmarks" on public.bookmarks
for insert with check (auth.uid() = user_id);

create policy "users delete own bookmarks" on public.bookmarks
for delete using (auth.uid() = user_id);

-- Admin mutations are performed through server routes protected by ADMIN_LOGIN_CODE.
-- Create a public storage bucket named post-images in Supabase Storage.
